-- Run on the warehouse database after sql/03-etl-functions.sql.
-- Modes/groups are a starting point. Tune after observing row counts and load.
-- include_deleted=true keeps soft deletes in raw.* so marts can decide filtering.

INSERT INTO etl.replication_tables (
  table_name,
  refresh_mode,
  refresh_group,
  enabled,
  include_deleted,
  lookback,
  priority,
  notes
)
VALUES
  ('facility_facility', 'full', 'daily', true, true, interval '2 hours', 10, 'Facility dimension'),
  ('facility_facilityflag', 'full', 'daily', true, true, interval '2 hours', 20, 'Facility feature flags'),
  ('facility_patientmobileotp', 'full', 'excluded', false, true, interval '2 hours', 999, 'Sensitive ephemeral OTP table; excluded by default'),
  ('emr_organization', 'full', 'daily', true, true, interval '2 hours', 30, 'Geo organization dimension'),
  ('emr_facilityorganization', 'full', 'daily', true, true, interval '2 hours', 31, 'Facility organization dimension'),
  ('emr_organizationuser', 'incremental', 'daily', true, true, interval '2 hours', 32, 'Organization user access mapping'),
  ('emr_facilityorganizationuser', 'incremental', 'daily', true, true, interval '2 hours', 33, 'Facility organization user access mapping'),
  ('emr_facilitylocation', 'incremental', 'hourly', true, true, interval '2 hours', 40, 'Facility locations'),
  ('emr_facilitylocationorganization', 'incremental', 'daily', true, true, interval '2 hours', 41, 'Location organization mapping'),
  ('emr_facilitylocationencounter', 'incremental', 'hourly', true, true, interval '2 hours', 42, 'Location encounter history'),
  ('emr_patient', 'incremental', 'hourly', true, true, interval '2 hours', 50, 'Patient master'),
  ('emr_patientorganization', 'incremental', 'hourly', true, true, interval '2 hours', 51, 'Patient organization mapping'),
  ('emr_patientuser', 'incremental', 'hourly', true, true, interval '2 hours', 52, 'Patient user mapping'),
  ('emr_patientidentifierconfig', 'full', 'daily', true, true, interval '2 hours', 53, 'Patient identifier configuration'),
  ('emr_patientidentifier', 'incremental', 'hourly', true, true, interval '2 hours', 54, 'Patient identifiers'),
  ('emr_encounter', 'incremental', 'hourly', true, true, interval '2 hours', 60, 'Encounter fact'),
  ('emr_encounterorganization', 'incremental', 'hourly', true, true, interval '2 hours', 61, 'Encounter organization mapping'),
  ('emr_condition', 'incremental', 'hourly', true, true, interval '2 hours', 70, 'Clinical condition'),
  ('emr_allergyintolerance', 'incremental', 'hourly', true, true, interval '2 hours', 71, 'Allergy intolerance'),
  ('emr_observation', 'incremental', 'hourly', true, true, interval '2 hours', 72, 'Observation fact; usually high volume'),
  ('emr_diagnosticreport', 'incremental', 'hourly', true, true, interval '2 hours', 73, 'Diagnostic report'),
  ('emr_servicerequest', 'incremental', 'hourly', true, true, interval '2 hours', 74, 'Service request'),
  ('emr_specimen', 'incremental', 'hourly', true, true, interval '2 hours', 75, 'Specimen'),
  ('emr_consent', 'incremental', 'hourly', true, true, interval '2 hours', 76, 'Consent'),
  ('emr_medicationrequestprescription', 'incremental', 'hourly', true, true, interval '2 hours', 80, 'Medication prescription grouping'),
  ('emr_medicationrequest', 'incremental', 'hourly', true, true, interval '2 hours', 81, 'Medication request'),
  ('emr_medicationstatement', 'incremental', 'hourly', true, true, interval '2 hours', 82, 'Medication statement'),
  ('emr_medicationadministration', 'incremental', 'hourly', true, true, interval '2 hours', 83, 'Medication administration'),
  ('emr_medicationdispense', 'incremental', 'hourly', true, true, interval '2 hours', 84, 'Medication dispense'),
  ('emr_dispenseorder', 'incremental', 'hourly', true, true, interval '2 hours', 85, 'Dispense order'),
  ('emr_account', 'incremental', 'hourly', true, true, interval '2 hours', 90, 'Billing account'),
  ('emr_chargeitem', 'incremental', 'hourly', true, true, interval '2 hours', 91, 'Charge item'),
  ('emr_invoice', 'incremental', 'hourly', true, true, interval '2 hours', 92, 'Invoice'),
  ('emr_paymentreconciliation', 'incremental', 'hourly', true, true, interval '2 hours', 93, 'Payment reconciliation'),
  ('emr_activitydefinition', 'full', 'daily', true, true, interval '2 hours', 100, 'Activity definition'),
  ('emr_observationdefinition', 'full', 'daily', true, true, interval '2 hours', 101, 'Observation definition'),
  ('emr_chargeitemdefinition', 'full', 'daily', true, true, interval '2 hours', 102, 'Charge item definition'),
  ('emr_resourcecategory', 'full', 'daily', true, true, interval '2 hours', 103, 'Resource/category tree'),
  ('emr_healthcareservice', 'full', 'daily', true, true, interval '2 hours', 104, 'Healthcare service'),
  ('emr_facilitymonetoryconfig', 'full', 'daily', true, true, interval '2 hours', 105, 'Facility billing config'),
  ('emr_productknowledge', 'full', 'daily', true, true, interval '2 hours', 110, 'Product knowledge'),
  ('emr_product', 'incremental', 'daily', true, true, interval '2 hours', 111, 'Product'),
  ('emr_inventoryitem', 'incremental', 'hourly', true, true, interval '2 hours', 112, 'Inventory item'),
  ('emr_supplyrequest', 'incremental', 'hourly', true, true, interval '2 hours', 113, 'Supply request'),
  ('emr_requestorder', 'incremental', 'hourly', true, true, interval '2 hours', 114, 'Request order'),
  ('emr_supplydelivery', 'incremental', 'hourly', true, true, interval '2 hours', 115, 'Supply delivery'),
  ('emr_deliveryorder', 'incremental', 'hourly', true, true, interval '2 hours', 116, 'Delivery order'),
  ('emr_device', 'incremental', 'hourly', true, true, interval '2 hours', 120, 'Device'),
  ('emr_deviceencounterhistory', 'incremental', 'hourly', true, true, interval '2 hours', 121, 'Device encounter history'),
  ('emr_devicelocationhistory', 'incremental', 'hourly', true, true, interval '2 hours', 122, 'Device location history'),
  ('emr_deviceservicehistory', 'incremental', 'hourly', true, true, interval '2 hours', 123, 'Device service history'),
  ('emr_schedulableresource', 'full', 'daily', true, true, interval '2 hours', 130, 'Schedulable resource'),
  ('emr_schedule', 'incremental', 'daily', true, true, interval '2 hours', 131, 'Schedule'),
  ('emr_availability', 'incremental', 'daily', true, true, interval '2 hours', 132, 'Availability'),
  ('emr_availabilityexception', 'incremental', 'daily', true, true, interval '2 hours', 133, 'Availability exception'),
  ('emr_tokenslot', 'incremental', 'hourly', true, true, interval '2 hours', 134, 'Token slot'),
  ('emr_tokenbooking', 'incremental', 'hourly', true, true, interval '2 hours', 135, 'Token booking'),
  ('emr_tokenqueue', 'full', 'daily', true, true, interval '2 hours', 136, 'Token queue'),
  ('emr_tokensubqueue', 'full', 'daily', true, true, interval '2 hours', 137, 'Token sub queue'),
  ('emr_tokencategory', 'full', 'daily', true, true, interval '2 hours', 138, 'Token category'),
  ('emr_token', 'incremental', 'hourly', true, true, interval '2 hours', 139, 'Token'),
  ('emr_questionnairetag', 'full', 'daily', true, true, interval '2 hours', 150, 'Questionnaire tag'),
  ('emr_questionnaire', 'full', 'daily', true, true, interval '2 hours', 151, 'Questionnaire'),
  ('emr_questionnaireorganization', 'full', 'daily', true, true, interval '2 hours', 152, 'Questionnaire organization mapping'),
  ('emr_questionnairefacilityorganization', 'full', 'daily', true, true, interval '2 hours', 153, 'Questionnaire facility organization mapping'),
  ('emr_questionnaireresponsetemplate', 'full', 'daily', true, true, interval '2 hours', 154, 'Questionnaire response template'),
  ('emr_formsubmission', 'incremental', 'hourly', true, true, interval '2 hours', 155, 'Form submission'),
  ('emr_questionnaireresponse', 'incremental', 'hourly', true, true, interval '2 hours', 156, 'Questionnaire response'),
  ('emr_valueset', 'full', 'daily', true, true, interval '2 hours', 160, 'ValueSet'),
  ('emr_uservaluesetpreference', 'incremental', 'daily', true, true, interval '2 hours', 161, 'User ValueSet preferences'),
  ('emr_tagconfig', 'full', 'daily', true, true, interval '2 hours', 162, 'Tag configuration'),
  ('emr_template', 'full', 'daily', true, true, interval '2 hours', 170, 'Report template'),
  ('emr_reportupload', 'incremental', 'hourly', true, true, interval '2 hours', 171, 'Report upload metadata'),
  ('emr_fileupload', 'incremental', 'hourly', true, true, interval '2 hours', 172, 'File upload metadata'),
  ('emr_notethread', 'incremental', 'hourly', true, true, interval '2 hours', 180, 'Note thread'),
  ('emr_notemessage', 'incremental', 'hourly', true, true, interval '2 hours', 181, 'Note message'),
  ('emr_metaartifact', 'incremental', 'daily', true, true, interval '2 hours', 190, 'Metadata artifact'),
  ('emr_userresourcefavorites', 'incremental', 'daily', true, true, interval '2 hours', 191, 'User resource favorites'),
  ('emr_specimendefinition', 'full', 'daily', true, true, interval '2 hours', 192, 'Specimen definition'),
  ('emr_resourcerequest', 'incremental', 'hourly', true, true, interval '2 hours', 200, 'Resource request'),
  ('emr_resourcerequestcomment', 'incremental', 'hourly', true, true, interval '2 hours', 201, 'Resource request comment')
ON CONFLICT (table_name) DO UPDATE SET
  refresh_mode = EXCLUDED.refresh_mode,
  refresh_group = EXCLUDED.refresh_group,
  enabled = EXCLUDED.enabled,
  include_deleted = EXCLUDED.include_deleted,
  lookback = EXCLUDED.lookback,
  priority = EXCLUDED.priority,
  notes = EXCLUDED.notes;

